language: node_js
node_js: 11.10.0
os:
  - linux
before_script:
  - npm install -g gulp
  - npm install
script: gulp

cache:
  directories:
    - "node_modules"

before_deploy:
  - pwd
  - ls dist/js/
  
deploy:
  - provider: releases
    api_key:
      secure: ""
    file:
      - dist/js/vis-networkman.min.js
      - dist/css/vis-networkman.min.css
    skip_cleanup: true
    on:
      repo: sj-js/vis-networkman
      branch: master
  - provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_API_TOKEN"
    skip_cleanup: true
    on:
      branch: master